# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('site', models.URLField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PestIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(blank=True, max_length=500, null=True)),
                ('plant_type', models.CharField(choices=[('FL', 'Flower'), ('VG', 'Vegetable'), ('SH', 'Shrub'), ('TR', 'Tree')], default='FL', max_length=255)),
                ('bloom_color', models.CharField(blank=True, max_length=255, null=True)),
                ('best_use', models.CharField(choices=[('LA', 'Large Arrangement'), ('SA', 'Small Arrangement'), ('BF', 'Body Flower / Corsage'), ('LO', 'Landscape Only')], default='LA', max_length=255)),
                ('stem_length', models.FloatField(default=1)),
                ('stem_length_units', models.CharField(choices=[('IN', 'Inches'), ('FT', 'Feet'), ('CM', 'Centimeters'), ('MT', 'Meters')], default='IN', max_length=255)),
                ('hardiness_zone', models.CharField(choices=[('1A', '1A'), ('1B', '1B'), ('2A', '2A'), ('2B', '2B'), ('3A', '3A'), ('3B', '3B'), ('4A', '4A'), ('4B', '4B'), ('5A', '5A'), ('5B', '5B'), ('6A', '6A'), ('6B', '6B'), ('7A', '7A'), ('7B', '7B'), ('8A', '8A'), ('8B', '8B'), ('9A', '9A'), ('9B', '9B'), ('10A', '10A'), ('10B', '10B'), ('11A', '11A'), ('11B', '11B'), ('12A', '12A'), ('12B', '12B'), ('13A', '13A'), ('13B', '13B')], default='1A', max_length=255)),
                ('bloom_time', models.DateField(auto_now_add=True)),
                ('availability', models.CharField(choices=[('SD', 'Seed'), ('PL', 'Plug'), ('PP', 'Potted Plant')], max_length=255)),
                ('seed_prep', models.CharField(blank=True, max_length=255, null=True)),
                ('germination', models.CharField(choices=[('NL', 'Needs Light'), ('ND', 'Needs Darkness'), ('NA', 'Neither')], max_length=255)),
                ('seedling_image', filebrowser.fields.FileBrowseField(blank=True, max_length=300, null=True)),
                ('light_req', models.TextField(blank=True, help_text='Light Requirements Following Germination', max_length=10000, null=True)),
                ('temp_req', models.TextField(blank=True, help_text='Temperature Requirements for Germination and Root Development', max_length=10000, null=True)),
                ('harvest_time_start', models.DateField(auto_now_add=True)),
                ('harvest_time_end', models.DateField(auto_now_add=True)),
                ('cond_methods', models.CharField(blank=True, help_text='Conditioning Methods', max_length=255, null=True)),
                ('tips_and_tricks', models.TextField(blank=True, max_length=10000, null=True)),
                ('source', models.ManyToManyField(to='plants.MaterialSource')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=500)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant')),
            ],
        ),
        migrations.AddField(
            model_name='pestissue',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
    ]
