# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-16 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plantevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantevent',
            name='details',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
