# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-16 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plantevent_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantevent',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plants.Plant'),
        ),
    ]
