# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_auto_20170716_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantevent',
            name='color',
            field=models.CharField(blank=True, default='1bc974', help_text='This will be the color of the event on the dashboard calendar', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='plantevent',
            name='text_color',
            field=models.CharField(blank=True, default='fff', help_text='This will be the color the event text on the dashboard calendar', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='plantevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('PT', 'Plant Seeds'), ('MV', 'Move Plants'), ('PR', 'Prune Plants'), ('HV', 'Harvest'), ('OT', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantevent',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Plant seeds, Move to larger pot, etc.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plantevent',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='plants.Plant'),
        ),
    ]
