# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-07-17 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_userplant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userplant',
            unique_together=set([('user', 'plant')]),
        ),
    ]
