# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-06 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_auto_20170717_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='availability',
            field=models.CharField(choices=[('SD', 'Seed'), ('PL', 'Plug'), ('PP', 'Potted Plant')], default='SD', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='bloom_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='germination',
            field=models.CharField(choices=[('NL', 'Needs Light'), ('ND', 'Needs Darkness'), ('NA', 'Neither')], default='NL', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvest_time_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='harvest_time_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='source',
            field=models.ManyToManyField(blank=True, null=True, to='plants.MaterialSource'),
        ),
    ]
