# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_auto_20170806_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='usda_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
