# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_plant_usda_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
