# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0012_plantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
