# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-09 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0013_plantimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='images'),
        ),
    ]
