# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-12 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_auto_20170808_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='bloom_color',
            new_name='flower_color',
        ),
        migrations.AddField(
            model_name='plant',
            name='foliage_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='source',
            field=models.ManyToManyField(to='plants.MaterialSource'),
        ),
    ]
