# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20170812_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='lifespan',
            field=models.CharField(choices=[('P', 'Perennial'), ('B', 'Biennial'), ('A', 'Annual')], default='P', max_length=255),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('HB', 'Herb'), ('SH', 'Shrub'), ('TR', 'Tree'), ('GR', 'Grass')], default='FL', max_length=255),
        ),
    ]
