# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0017_auto_20170813_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='plant_type',
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_habit',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
