# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-14 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0018_auto_20170814_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='lifespan',
        ),
        migrations.AddField(
            model_name='plant',
            name='annual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='biennial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='perennial',
            field=models.BooleanField(default=False),
        ),
    ]
