# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-20 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0019_auto_20170814_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
