# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-20 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0021_auto_20170819_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ('scientific_name',), 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
