# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-20 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0022_auto_20170819_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plants.Plant'),
        ),
    ]
