# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-20 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0025_auto_20170919_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('user_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.UserPlant')),
            ],
            options={
                'ordering': ('user_plant', 'create_date'),
                'verbose_name': 'Plant Task',
                'verbose_name_plural': 'Plant Tasks',
            },
        ),
    ]
